const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),ts=require('typescript');
const ast=ts.createSourceFile('App.tsx',fs.readFileSync('src/App.tsx','utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let handler;
function visit(n){if(ts.isVariableDeclaration(n)&&n.name.getText(ast)==='handleMaintenanceResume')handler=n.initializer.getText(ast);ts.forEachChild(n,visit);}visit(ast);assert(handler);
const code=ts.transpileModule('('+handler+')',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
function setup(){const calls=[];const c={maintenanceClient:async()=>({ownsMerge:false}),isStartupLauncherOpenRef:{current:false},isInitialLoaded:true,safeStorage:{getItem:()=>'{"id":"sheet"}'},getAccessToken:async()=> 'token',isSyncInProgressRef:{current:false},isCleanWritingRef:{current:false},isImportingRef:{current:false},pendingAudit:async()=>[],idbGet:async()=>null,getSheetsPayload:v=>v,syncStateRef:{current:{households:[]}},loadDeletedRecordsLog:()=>[],writeSafetyRef:{current:{baseline:'verified',hasPending:()=>false,block:()=>calls.push(['blocked'])}},setSyncStatus:s=>calls.push(['status',s]),setSyncErrorMessage:m=>calls.push(['error',m]),syncWithGoogleDriveRef:{current:async(...args)=>calls.push(['read',...args])}};return {c,calls,run:vm.runInNewContext(code,c)};}
test('maintenance completion does not merge launcher defaults with a populated remote sheet',async()=>{const {c,calls,run}=setup();c.isStartupLauncherOpenRef.current=true;c.getAccessToken=async()=>{throw Error('launcher must not start synchronization');};await run();assert.deepEqual(calls,[]);});
test('saved 20,000-record session resumes maintenance with a read-only import, without a merge',async()=>{const {c,calls,run}=setup();c.syncStateRef.current.households=Array.from({length:20000},(_,i)=>({id:'H'+i}));await run();assert.deepEqual(calls,[['read','token','sheet',true]]);});
test('unsent edits, uncertain writes, missing baseline and pending audit never get discarded by maintenance',async()=>{for(const kind of ['edit','uncertain','baseline','audit']){const {c,calls,run}=setup();if(kind==='edit')c.writeSafetyRef.current.hasPending=()=>true;if(kind==='uncertain')c.idbGet=async()=>({expected:{}});if(kind==='baseline')c.writeSafetyRef.current.baseline=null;if(kind==='audit')c.pendingAudit=async()=>[{logId:'unsent'}];await assert.rejects(run(),/未送信または未確認/);assert(!calls.some(c=>c[0]==='read'));assert(calls.some(c=>c[0]==='blocked'));}});
test('maintenance does not launch another read while a save is still running',async()=>{const {c,calls,run}=setup();c.isSyncInProgressRef.current=true;await run();assert.deepEqual(calls,[]);});
