const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),ts=require('typescript');
const source=fs.readFileSync('src/App.tsx','utf8'),ast=ts.createSourceFile('App.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let handler;
function visit(n){if(ts.isVariableDeclaration(n)&&n.name.getText(ast)==='handleManualSync')handler=n.initializer.getText(ast);ts.forEachChild(n,visit);}visit(ast);assert(handler);
const code=ts.transpileModule('('+handler+')',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
function setup(token='token',sheet={id:'configured'}){const calls=[];const c={manualSyncInProgressRef:{current:false},isSyncInProgressRef:{current:false},isCleanWritingRef:{current:false},loadJsonState:()=>sheet,setSyncErrorMessage:m=>calls.push(['error',m]),setIsGoogleSheetsModalOpen:v=>calls.push(['settings',v]),setIsManualSyncPending:v=>calls.push(['busy',v]),setSyncStatus:v=>calls.push(['status',v]),getAccessToken:async()=>token,googleSignIn:async()=>{calls.push(['login']);return {accessToken:'renewed'};},syncWithGoogleDrive:async(...args)=>calls.push(['read',...args]),isAuthError:()=>false,clearCachedAccessToken(){}};return {c,calls,run:vm.runInNewContext(code,c)};}
test('history sync checks the configured sheet without opening settings',async()=>{const {run,calls}=setup();await run();assert.deepEqual(calls.find(c=>c[0]==='read'),['read','token','configured']);assert(!calls.some(c=>c[0]==='settings'||c[0]==='login'));});
test('expired login continues directly to the same sheet after authentication',async()=>{const {run,calls}=setup(null);await run();assert.deepEqual(calls.find(c=>c[0]==='read'),['read','renewed','configured']);assert(!calls.some(c=>c[0]==='settings'));});
test('repeated clicks do not create overlapping login or sync; failures are displayed and release busy state',async()=>{const {run,c,calls}=setup();let reject;c.syncWithGoogleDrive=()=>new Promise((_,r)=>{reject=r;});const pending=run();await new Promise(setImmediate);await run();reject(Error('HTTP 429'));await pending;assert.equal(calls.filter(c=>c[0]==='busy'&&c[1]).length,1);assert(calls.some(c=>c[0]==='error'&&c[1]==='HTTP 429'));assert.equal(c.manualSyncInProgressRef.current,false);assert.deepEqual(calls.at(-1),['busy',false]);});
test('missing destination opens setup, and cancelled login never starts reading',async()=>{const missing=setup('token',null);await missing.run();assert(missing.calls.some(c=>c[0]==='settings'));assert(!missing.calls.some(c=>c[0]==='read'));const cancelled=setup(null);cancelled.c.googleSignIn=async()=>null;await cancelled.run();assert(!cancelled.calls.some(c=>c[0]==='read'));assert(cancelled.calls.some(c=>c[0]==='error'&&c[1]?.includes('キャンセル')));});

test('reconnect explicitly replaces an expired cached token and never requests startup reset',async()=>{const {run,calls}=setup('expired');await run(true);assert(calls.some(c=>c[0]==='login'));assert.deepEqual(calls.find(c=>c[0]==='read'),['read','renewed','configured']);});
